<?php

/**
 * FileSystem Env Repository
 *
 * Handles .env file operations for database connection wizard.
 * This repository does NOT require a database connection.
 *
 * PHP version 8.1
 *
 * @category Lukaisu
 * @package  Lukaisu\Modules\Admin\Infrastructure
 * @author   HugoFara <hugo.farajallah@protonmail.com>
 * @license  Unlicense <http://unlicense.org/>
 * @link     https://hugofara.github.io/lukaisu-server/developer/api
 * @since    3.0.0
 */

declare(strict_types=1);

namespace Lukaisu\Modules\Admin\Infrastructure;

use Lukaisu\Modules\Admin\Application\DTO\DatabaseConnectionDTO;

/**
 * FileSystem repository for .env file operations.
 *
 * Provides file system access for database connection wizard.
 * This class operates independently of the database.
 *
 * @since 3.0.0
 */
class FileSystemEnvRepository
{
    /**
     * Path to the .env file.
     *
     * @var string
     */
    private string $envPath;

    /**
     * Constructor.
     *
     * @param string|null $basePath Base path for .env file (default: Lukaisu Server root)
     */
    public function __construct(?string $basePath = null)
    {
        if ($basePath === null) {
            $basePath = dirname(__DIR__, 4); // Go up from Modules/Admin/Infrastructure to Lukaisu Server root
        }
        $this->envPath = $basePath . '/.env';
    }

    /**
     * Check if .env file exists.
     *
     * @return bool True if file exists
     */
    public function exists(): bool
    {
        return file_exists($this->envPath);
    }

    /**
     * Get .env file path.
     *
     * @return string Path to .env file
     */
    public function getPath(): string
    {
        return $this->envPath;
    }

    /**
     * Load connection from .env file.
     *
     * @return DatabaseConnectionDTO Connection data
     */
    public function load(): DatabaseConnectionDTO
    {
        $dto = new DatabaseConnectionDTO();

        if (!$this->exists()) {
            return $dto;
        }

        $lines = file($this->envPath, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
        if ($lines === false) {
            return $dto;
        }

        foreach ($lines as $line) {
            if (strpos(trim($line), '#') === 0) {
                continue;
            }
            if (strpos($line, '=') === false) {
                continue;
            }

            $parts = explode('=', $line, 2);
            $key = trim($parts[0]);
            $value = $this->unquoteEnvValue(trim($parts[1] ?? ''));

            switch ($key) {
                case 'DB_HOST':
                    $dto->server = $value;
                    break;
                case 'DB_USER':
                    $dto->userid = $value;
                    break;
                case 'DB_PASSWORD':
                    $dto->passwd = $value;
                    break;
                case 'DB_NAME':
                    $dto->dbname = $value;
                    break;
                case 'DB_SOCKET':
                    $dto->socket = $value;
                    break;
            }
        }

        return $dto;
    }

    /**
     * Save connection to .env file.
     *
     * @param DatabaseConnectionDTO $dto Connection data to save
     *
     * @return bool True on success
     */
    public function save(DatabaseConnectionDTO $dto): bool
    {
        $content = "# Lukaisu Server Database Configuration\n";
        $content .= "# Generated by Database Connection Wizard\n\n";
        $content .= "DB_HOST=" . $this->quoteEnvValue($dto->server) . "\n";
        $content .= "DB_USER=" . $this->quoteEnvValue($dto->userid) . "\n";
        $content .= "DB_PASSWORD=" . $this->quoteEnvValue($dto->passwd) . "\n";
        $content .= "DB_NAME=" . $this->quoteEnvValue($dto->dbname) . "\n";

        if (!empty($dto->socket)) {
            $content .= "DB_SOCKET=" . $this->quoteEnvValue($dto->socket) . "\n";
        }

        $handle = fopen($this->envPath, 'w');
        if ($handle === false) {
            return false;
        }

        $result = fwrite($handle, $content);
        fclose($handle);

        return $result !== false;
    }

    /**
     * Get autocomplete values from server environment.
     *
     * @return DatabaseConnectionDTO Pre-filled connection data
     */
    public function getAutocompleteSuggestions(): DatabaseConnectionDTO
    {
        return new DatabaseConnectionDTO(
            server: $_SERVER['SERVER_ADDR'] ?? 'localhost',
            userid: '',
            passwd: '',
            dbname: $_SERVER['SERVER_NAME'] ?? 'lukaisu',
            socket: ''
        );
    }

    /**
     * Test a database connection.
     *
     * @param DatabaseConnectionDTO $dto Connection data to test
     *
     * @return array{success: bool, error: ?string}
     */
    public function testConnection(DatabaseConnectionDTO $dto): array
    {
        $mysqli = mysqli_init();
        if ($mysqli === false) {
            return ['success' => false, 'error' => "MySQL is not accessible!"];
        }

        try {
            if ($dto->socket != "") {
                $success = @mysqli_real_connect(
                    $mysqli,
                    $dto->server,
                    $dto->userid,
                    $dto->passwd,
                    $dto->dbname,
                    socket: $dto->socket
                );
            } else {
                $success = @mysqli_real_connect(
                    $mysqli,
                    $dto->server,
                    $dto->userid,
                    $dto->passwd,
                    $dto->dbname
                );
            }

            if (!$success) {
                return ['success' => false, 'error' => "Can't connect!"];
            } elseif (mysqli_errno($mysqli) != 0) {
                return [
                    'success' => false,
                    'error' => "ERROR: " . mysqli_error($mysqli) .
                        " error number: " . mysqli_errno($mysqli)
                ];
            }

            mysqli_close($mysqli);
            return ['success' => true, 'error' => null];
        } catch (\Exception $except) {
            return ['success' => false, 'error' => (string) $except];
        }
    }

    /**
     * Quote an env value for safe storage.
     *
     * Always uses double quotes and escapes special characters.
     *
     * @param string $value Raw value
     *
     * @return string Quoted and escaped value
     */
    private function quoteEnvValue(string $value): string
    {
        // Escape backslashes first, then double quotes and dollar signs
        $escaped = str_replace(
            ['\\', '"', '$'],
            ['\\\\', '\\"', '\\$'],
            $value
        );
        return '"' . $escaped . '"';
    }

    /**
     * Unquote an env value when loading.
     *
     * Handles both single and double quoted values, and unescapes characters.
     *
     * @param string $value Quoted value from .env file
     *
     * @return string Unquoted and unescaped value
     */
    private function unquoteEnvValue(string $value): string
    {
        $len = strlen($value);
        if ($len < 2) {
            return $value;
        }

        $first = $value[0];
        $last = $value[$len - 1];

        // Handle double-quoted values
        if ($first === '"' && $last === '"') {
            $unquoted = substr($value, 1, -1);
            // Unescape in reverse order: dollar, quotes, backslashes
            return str_replace(
                ['\\$', '\\"', '\\\\'],
                ['$', '"', '\\'],
                $unquoted
            );
        }

        // Handle single-quoted values (no escape processing)
        if ($first === "'" && $last === "'") {
            return substr($value, 1, -1);
        }

        return $value;
    }
}
